---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#prod
resources:
- ../../base 

labels:
- pairs:
    env: prod
  includeSelectors: true
  includeTemplates: true
namePrefix: prod-
namespace: prod-ns

replicas:
- name: dov-deploy
  count: 3

images:
- name: chukmunnlee/dov-bear
  newTag: v5-prod

# to run kustomization for config, secret
# kubectl apply -k -oyaml --dry-run=client
# can add :.! in vim to apply output direct to vim file

patches:
- target: 
    group: apps
    version: v1
    kind: Deployment
    name: dov-deploy
  path: patch.yml
