# to run this file, docker compose up -d
volumes:
  # docker volume create data-vol
  data-vol:

networks:
  # docker network create mynet
  mynet:

services:
  # docker run -d --name=mydb --network=mynet --mount type=volume,src=data-vol,dst=/ar/lib/mysql \
  # hoholyin/mydb:v1.0
  northwind-db:
    image: stackupiss/northwind-db:v1
    build:
      context: database
      # if dockerfile is another name, 
      # dockerfile: dockerfile_name
    volumes:
    - data-vol:/var/lib/mysql
    networks:
    - mynet

  # docker run -d -p 8000-9000:3000 --nwtwork=mynet \
  # -e DB_HOST=mydb -e DB_USER=root -e DB_PASSWORD=changeit \
  # hoholyin/myapp:v1.0
  northwind-app:
    image: stackupiss/northwind-app:v1
    build:
      context: server  
    environment:
    - DB_HOST=mydb
    - DB_USER=root
    - DB_PASSWORD=changeit
    networks:
    - mynet
    ports:
    - 8000-9000
    depends_on:
    - northwind-db 

