---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy
  namespace: myns
  labels:
    app: dov
    name: dov-deploy

spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
      dept: eng
      commit: abc123
  template:
    # all pod information in template
    metadata:
      name: mypod
      namespace: myns
      labels:
        app: myapp
        dept: eng
        commit: abc123
    spec:
      containers:
      - name: mypod-container
        image: chukmunnlee/dov-bear:v5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: INSTANCE_NAME
          value: my first pod
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pod-template-hash']

--- 
apiVersion: v1
kind: Service
metadata: 
  name: dov-svc
  namespace: myns
  labels:
    app: dov
    name: dov-svc
spec:
  type: ClusterIP
  selector: 
    app: myapp
    dept: eng
    commit: abc123
  ports:
  - port: 8000
    targetPort: 3000 # refers to on top the 
