---
apiVersion: v1
kind: Namespace
metadata:
  name: myns

---
# pod
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: myns
  labels:
    app: myapp
spec:
  containers:
  - name: mypod-container
    image: chukmunnlee/dov-bear:v5
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3000
    env:
    - name: INSTANCE_NAME
      value: my first pod
    - name: INSTANCE_HASH
      value: abcd1234

