---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- dov.yml

configMapGenerator:
- name: dov-cm
  namespace: dovns
  behavior: create
  literals:
  - INSTANCE_NAME=prod-version
